### PR TITLE
CSS tweaks

### PR DESCRIPTION
**Pull request by yochannah**
okay - I think the CSS tweakage will be an ongoing work for now. This PR addresses: 

- #19 - all caps headers
- #18 - there is a max width for BOSC page styles. This behaviour may need to be added in other places too. 

Plenty more needs to be done but I think this is a respectable chunk. The changes are relatively low-risk and should be safe to deploy to prod I think (famous last words, I know) - they're largely font sizes, with some padding and margins, and _one_ html class change. HUGE thanks to @peterjc and @heuermh for the visual feedback to get here. 

Example collaborationfest page, before:

image

after:
image

### CODE REVIEW

**Comment by yochannah** [comment]
This also fixes https://github.com/OBF/homepage/issues/16

**Comment by heuermh** [comment]
Looks pretty good to me!

On the CoFest page I last tried bumping the headings up to H1/H2 from what they had been before (H3/H4 probably), so with this new CSS they could go back down if they are too big relative to the paragraph text size.

**Comment by nlharris** [comment]
That looks much better--thank you!! We'll need to check all the pages after you make the change, because some layout stuff, picture sizes, etc. may need adjusting.

**Comment by peterjc** [comment]
I agree, based on the screenshots this is a worthy improvement. The risk assessment seems fine too - let’s merge it?

**Comment by peterjc** [comment]
The current ``README.md`` description is not clear to me, but I gather some (manual?) deployment step is required after the git merge?

**Comment by peterjc** [comment]
Documenting deployment logged as #23.

**Pull request merged**
